version: '3.5'

services:
  app:
    env_file: .env
    build:
      dockerfile: .docker/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
      context: .
    volumes:
      - ./core:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php-overrides.ini
    working_dir: /var/www
    container_name: ${APP_CONTAINER_NAME}
    depends_on:
      - mysql
    networks:
      - ${NETWORK_NAME}

  nginx:
    env_file: .env
    image: nginx:alpine
    container_name: ${MAIN_NGINX_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${MAIN_NGINX_PORT}:80
    volumes:
      - ./core:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      - ${NETWORK_NAME}
  mysql:
    env_file: .env
    image: mysql:5.7
    restart: unless-stopped
    container_name: ${MAIN_DB_CONTAINER_NAME}
    ports:
      - "${MAIN_DB_PORT}:3306"
    volumes:
      - "./.docker-data/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${MAIN_DB_NAME}
      MYSQL_USER: ${MAIN_DB_USER}
      MYSQL_PASSWORD: ${MAIN_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MAIN_DB_PASSWORD}
    networks:
      - ${NETWORK_NAME}

networks:
  task-network:
    name: ${NETWORK_NAME}
    external: true
    driver: bridge
